# Generated by Django 3.2.9 on 2022-05-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erevan_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderReasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='headerdescription',
            name='header',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headerdescription',
            name='subheader',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
