# Generated by Django 3.2.9 on 2022-04-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='name',
            field=models.CharField(default='Test', max_length=150, verbose_name='Вопрос'),
            preserve_default=False,
        ),
    ]
