# Generated by Django 3.2.9 on 2022-04-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_element_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('one_in_list', 'Один из списка'), ('many_in_list', 'Неколько из списка'), ('string', 'Строка'), ('textarea', 'Текст с абзацами'), ('range', 'Шкала')], max_length=20, verbose_name='Тип элемента'),
        ),
    ]
