# Generated by Django 3.2.9 on 2022-04-30 17:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_element_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='access',
            field=models.CharField(choices=[('link', 'Только по ссылке'), ('opened', 'Открыт всем')], default='link', max_length=20, verbose_name='Разрешение'),
        ),
        migrations.AddField(
            model_name='survey',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
